[general]
enable_bucket = true                        # 是否使用Aspect Ratio Bucketing

[[datasets]]
resolution = 512                            # 训练分辨率
batch_size = 1                              # 批次大小

  [[datasets.subsets]]
  image_dir = 'train/datasets/scircle'                     # 指定包含训练图像的文件夹
  caption_extension = '.txt'            # 若使用txt文件,更改此项
  class_tokens = 'abstract circle'                # 指定标识符类
  num_repeats = 10                          # 训练图像的重复次数
