##### 模型选择: default:SD;  SD3;  Flux
model_type = "flux"

#------------------------------------- if modelType == SD -------------------------------------
### 任务选择
task = "t2i"
has_lora = true
has_controlnet = false
version = "v1"  # v1/v2/sdxl

[general]
### 基础配置
# ckpt = "/home/ps/sdbench/models/1.ckpt" # 绝对路径
ckpt = "/home/ps/sdbench/models/sd_xl.safetensors"
prompt = "mysterious anime girl with silver hair and heterochromia eyes, wearing a gothic lolita dress, standing under a glowing cherry blossom tree, illuminated by soft moonlight, ultra-detailed, fantasy lighting, cinematic shot"
negative_prompt = ""
step = 50
images_per_prompt = 50
sampler = "k_dpm_2"
scale = 7.5
outdir = "outputs"
n_iter = 10
H = 512
W = 512
batch_size = 1
# seed = 1
clip_skip = 2
fp16 = true
xformers = true

# ### img2img
# [img2img]
# image_path = "1.png"
# strength = 0.7
# use_original_file_name = true
# ### inpainting
# [inpainting]
# mask_path = "1.png"


### additional network (LoRA)
# [lora]
# network_module = ["networks.lora"]
# network_weights = ["models/lora/sdxl/chinese_painting-40.safetensors"]
# network_mul = [0.8]


### controlnet配置
# [controlnet]
# control_net_models = "diff_control_sd15_canny.safetensors"
# control_net_weights = 1.0
# guide_image_path = "guide.png"
# control_net_ratios = 1.0




#------------------------------------- if modelType == Flux -------------------------------------

[flux]
ckpt = "models/flux/flux1-dev.sft"
clip_l = "models/flux/clip_l.safetensors"
t5xxl = "models/flux/t5xxl_fp16.safetensors"
ae = "models/flux/ae.sft"
dtype = "bf16"
prompt = "mysterious anime girl with silver hair and heterochromia eyes, wearing a gothic lolita dress, standing under a glowing cherry blossom tree, illuminated by soft moonlight, ultra-detailed, fantasy lighting, cinematic shot"
negative_prompt = ""
output = "outputs"
#seed = 4
flux_dtype = "fp8"
offload = true
width = 1024
height = 1024
steps = 50
guidance = 3.5
cfg_scale = 1.0
n_samples = 1

# lora_model_path = ["/home/ps/sdbench/train/output/flux/chinese_painting_new/chinese_painting-000030.safetensors"]
# lora_weight = [0.7]

#lora_model_path = ["models/lora/fluxlora/chinese_painting-20.safetensors","models/test.safetensors"]
#lora_weight = [1.0,1.0]

# ------------------------------------- if modelType == SD3 -------------------------------------
[SD3]
ckpt = "models/sd3/sd3.5_medium.safetensors"
clip_g = "models/sd3/clip_g.safetensors"
clip_l = "models/flux/clip_l.safetensors"
t5xxl = "models/flux/t5xxl_fp16.safetensors"
#t5xxl_token_length = 256
prompt = "mysterious anime girl with silver hair and heterochromia eyes, wearing a gothic lolita dress, standing under a glowing cherry blossom tree, illuminated by soft moonlight, ultra-detailed, fantasy lighting, cinematic shot"
negative_prompt = ""
output = "outputs"
offload = true
bf16 = true
#seed = 4
width = 1024
height = 1024
steps = 50
n_samples = 5

# lora_model_path = ["models/lora/sd3lora/chinese_painting-40.safetensors"]
# lora_weight = [1.0]

#[SDXL]
#ckpt = "models/sd_xl.safetensors"
#prompt = "a cat holding a sign that says hello world"
#prompt2 = ""
#negative_prompt = ""
#output = "outputs"
#seed = 4
#width = 1024
#height = 1024
#steps = 50
#guidance_scale = 3.5



