##### 模型选择: default:SD;  SD3;  Flux
model_type = "SD"

#------------------------------------- if modelType == SD -------------------------------------
### 任务选择
task = "t2i"
has_lora = true
has_controlnet = false
version = "sdxl"  # v1/v2/sdxl

[general]
### 基础配置
# ckpt = "/home/ps/sdbench/models/1.ckpt" # 绝对路径
ckpt = "/home/ps/sdbench/models/sd_xl.safetensors"
prompt = "A traditional Chinese landscape painting depicting misty mountains, calm water, and a small wooden boat with a person aboard. The mountains in the background are green and gray, shrouded in soft mist, while the foreground features lush hills and pine trees. The painting uses delicate brush strokes, subtle ink wash shading, and a serene color palette of blues, greens, and grays, evoking a tranquil and ethereal atmosphere typical of classic Chinese watercolor art."
negative_prompt = ""
step = 50
images_per_prompt = 50
sampler = "k_dpm_2"
scale = 7.5
outdir = "outputs"
n_iter = 10
H = 512
W = 512
batch_size = 1
# seed = 1
clip_skip = 2
fp16 = true
xformers = true
### img2img
[img2img]
image_path = "1.png"
strength = 0.7
use_original_file_name = true
### inpainting
[inpainting]
mask_path = "1.png"
### additional network (LoRA)
[lora]
network_module = ["networks.lora"]
network_weights = ["models/lora/sdxl/chinese_painting-40.safetensors"]
network_mul = [0.8]
### controlnet配置
[controlnet]
control_net_models = "diff_control_sd15_canny.safetensors"
control_net_weights = 1.0
guide_image_path = "guide.png"
control_net_ratios = 1.0




#------------------------------------- if modelType == Flux -------------------------------------

[flux]
ckpt = "models/flux/flux1-dev.sft"
clip_l = "models/flux/clip_l.safetensors"
t5xxl = "models/flux/t5xxl_fp16.safetensors"
ae = "models/flux/ae.sft"
dtype = "bf16"
prompt = "A traditional Chinese landscape painting depicting misty mountains, calm water, and a small wooden boat with a person aboard. The mountains in the background are green and gray, shrouded in soft mist, while the foreground features lush hills and pine trees. The painting uses delicate brush strokes, subtle ink wash shading, and a serene color palette of blues, greens, and grays, evoking a tranquil and ethereal atmosphere typical of classic Chinese watercolor art."
negative_prompt = ""
output = "outputs"
#seed = 4
flux_dtype = "fp8"
offload = true
width = 1024
height = 1024
steps = 50
guidance = 3.5
cfg_scale = 1.0
n_samples = 1

# lora_model_path = ["models/lora/fluxlora/chinese_painting-30.safetensors"]
# lora_weight = [1.0]

#lora_model_path = ["models/lora/fluxlora/chinese_painting-20.safetensors","models/test.safetensors"]
#lora_weight = [1.0,1.0]

# ------------------------------------- if modelType == SD3 -------------------------------------
[SD3]
ckpt = "models/sd3/sd3.5_medium.safetensors"
clip_g = "models/sd3/clip_g.safetensors"
clip_l = "models/flux/clip_l.safetensors"
t5xxl = "models/flux/t5xxl_fp16.safetensors"
#t5xxl_token_length = 256
prompt = "A traditional Chinese landscape painting depicting misty mountains, calm water, and a small wooden boat with a person aboard. The mountains in the background are green and gray, shrouded in soft mist, while the foreground features lush hills and pine trees. The painting uses delicate brush strokes, subtle ink wash shading, and a serene color palette of blues, greens, and grays, evoking a tranquil and ethereal atmosphere typical of classic Chinese watercolor art."
negative_prompt = ""
output = "outputs"
offload = true
bf16 = true
#seed = 4
width = 1024
height = 1024
steps = 50
n_samples = 1

# lora_model_path = ["models/lora/sd3lora/chinese_painting-40.safetensors"]
# lora_weight = [1.0]

#[SDXL]
#ckpt = "models/sd_xl.safetensors"
#prompt = "a cat holding a sign that says hello world"
#prompt2 = ""
#negative_prompt = ""
#output = "outputs"
#seed = 4
#width = 1024
#height = 1024
#steps = 50
#guidance_scale = 3.5



