##### 模型选择: default: SD;  SD3;  Flux
model_type = "SDXL"

#------------------------------------- if modelType == SD -------------------------------------
[SD]
pretrained_model_name_or_path = "models/1.ckpt"
dataset_config = "configs/datasets.toml"
output_dir = "train/output"
output_name = "circle"
save_model_as = "safetensors"
prior_loss_weight = 1.0
max_train_steps = 400
learning_rate = 1e-4
optimizer_type = "AdamW8bit"
xformers = true
mixed_precision="fp16"
cache_latents = true
gradient_checkpointing = true
save_every_n_epochs=10
network_module="networks.lora"
logging_dir = "train/logs"

#------------------------------------- if modelType == SDXL -------------------------------------
[SDXL]
pretrained_model_name_or_path = "models/sd_xl.safetensors"
dataset_config = "configs/datasets.toml"
output_dir = "train/output"
output_name = "circle"
save_model_as = "safetensors"
prior_loss_weight = 1.0
max_train_steps = 400
learning_rate = 1e-4
optimizer_type = "AdamW8bit"
xformers = true
#mixed_precision="fp16"
cache_latents = true
gradient_checkpointing = true
save_every_n_epochs=10
network_module="networks.lora"
logging_dir = "train/logs"

#------------------------------------- if modelType == flux -------------------------------------
[flux]
pretrained_model_name_or_path = "models/flux/flux1-dev.sft"
clip_l = "models/flux/clip_l.safetensors"
t5xxl = "models/flux/t5xxl_fp16.safetensors"
ae =  "models/flux/ae.sft"
cache_latents_to_disk = true
save_model_as = "safetensors"
sdpa = true
persistent_data_loader_workers = true
max_data_loader_n_workers = 2
seed = 42
gradient_checkpointing = true
mixed_precision = "bf16"
save_precision = "bf16"
network_module = "networks.lora_flux"
network_dim = 4
optimizer_type = "adamw8bit"
sample_prompts = "hello"
sample_every_n_steps="100"
learning_rate = 8e-4
cache_text_encoder_outputs = true
cache_text_encoder_outputs_to_disk = true
fp8_base = true
highvram = true
max_train_epochs = 10
save_every_n_epochs = 4
dataset_config = "configs/datasets.toml"
output_dir = "train/output/flux"
output_name = "test"
timestep_sampling = "shift"
discrete_flow_shift = 3.1582
model_prediction_type =  "raw"
guidance_scale = 1
loss_type = "l2"

#------------------------------------- if modelType == SD3 -------------------------------------
[SD3]

pretrained_model_name_or_path = "models/sd3/sd3.5_medium.safetensors"
clip_l = "models/flux/clip_l.safetensors"
clip_g = "models/sd3/clip_g.safetensors"
t5xxl = "models/flux/t5xxl_fp16.safetensors"
cache_latents_to_disk = true
save_model_as = "safetensors"
sdpa = true
persistent_data_loader_workers = true
max_data_loader_n_workers = 2
seed = 42
gradient_checkpointing = true
mixed_precision = "bf16"
save_precision = "bf16"
network_module = "networks.lora_sd3"
network_dim = 4
network_train_unet_only = true
optimizer_type = "adamw8bit"
learning_rate = 1e-4
cache_text_encoder_outputs = true
cache_text_encoder_outputs_to_disk = true
fp8_base = true
highvram = true
max_train_epochs = 4
save_every_n_epochs = 2
dataset_config = "configs/datasets.toml"
output_dir = "outputs/sd3"
output_name = "sd3-lora-name"
